dist: trusty
sudo: false
language: node_js
node_js: 8.6.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.0
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add greenkeeper-lockfile@1
cache:
  yarn: true
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: rtsao@uber.com
  api_key:
    secure: sa0akEbPhFkiIlATJcV5oBDnkQu/IB7Nk1I5TzCXyNwO9JM3GufZsiq+slpor8NCz6Gd7/CbPIAoS/0XwbhH209u+mLkDI9Wv4P1fL6IdAOKld71oqyqwJfqHFTmbpivUZAuaWYvMU7b0n00PxPpBhPlOoZGjk3g1hkYGrAblbN5yK8fDazw+gGrj91c7wvOlh67wt4B4SVRlEjQ1r0PM7aSANWm5hOTknbf6uU/4gMryKLaVcNDhcsOth7MAihKGmpGCmlcIHMXcQACJ9NnsA9IFi6Tb9c+AOp3GH3kNzbxSc+1nweh4uxqk8fBfrZUou2h2zx/hHAzcEKXfJAPRXS78fkEy18XljuF3WhowxApYVGORrYMDRPDY2Y18IKIGx3XUNLDWZm7xq5ImKauyAKxq0KQCnlZsJIM3h7uKKD6DQzlqE409g5XxBOcR1oatucGXPeMQsXejFduw1D1e0DwPN6vmvSrWLMYh7iwezHfNe+qCJli42Nm4loPs2cnMQMnj+i2ohjvTsnX2rpTtsPY5l/8KlrgG3bVnnZbV0hGE/W/wustX1k8zxfqqoxRNxziaVrRh4oC6gL+dcahdtyPgL3qXeJJ4S8L+woavVtfX76rU+qesjX5ksihJDHVrLsZNoQp+ry6tH4EM0hVLUnoHDeY3RWZU6LKGt0jFAs=
  on:
    tags: true
    repo: uber-web/probot-app-todos
